name: Standart workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'

jobs:
          
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create .env file
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_DEBUG: false
        envkey_PORT: 8080
        fail_on_empty: false
        sort_keys: false
    
    - name: Build
      run: |
        npm install
        npm run build
