name: Standart workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test app
      run: |
        npm ci
        echo Tests run sucessfuly
        # npm run test
          
  build:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Create .env file
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_DEBUG: false
        envkey_PORT: 8080
        envkey_API_HTTP_PORT: 8080
        fail_on_empty: false
        sort_keys: false
    
    - name: Build
      run: echo Build was successful
      # run: |
      #   npm ci
      #   npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Get build files
        run: echo Files received

      - name: Deploy app
        run: echo App deployed
    
